### ISSUE TITLE
make遇错

### ISSUE THREAD

**Issue by luckypoem** [GangZhuo/http-proxy#1]
hi。

在mac上。
git clone https://github.com/GangZhuo/http-proxy http-proxy-by-GangZhuo
cd http-proxy-by-GangZhuo
git submodule init
git submodule update
make
it shows:
...
src/dnscache.h:30:28: error: unknown type name 'time_t'; did you mean 'size_t'?
void dnscache_check_expire(time_t now);
                           ^~~~~~
                           size_t
/usr/include/sys/_types/_size_t.h:30:32: note: 'size_t' declared here
typedef __darwin_size_t        size_t; 
                               ^
src/dnscache.c:228:6: error: conflicting types for 'dnscache_check_expire'
void dnscache_check_expire(time_t now)
     ^
src/dnscache.h:30:6: note: previous declaration is here
void dnscache_check_expire(time_t now);
     ^
2 errors generated.
make: *** [src/dnscache.o] Error 1
yudeMacBook-Air:http-proxy-by-GangZhuo brite$ 

怎么解决？

**Comment by GangZhuo** [comment]
请尝试下最新 master 分支.
