### ISSUE TITLE
命令行运行 http-proxy， CTRL+C 结束，需要很长时间才释放监听端口

### ISSUE THREAD

**Issue by rampageX** [GangZhuo/http-proxy#2]
系统是：Linux Debian-N1 5.0.2-aml-s905 #5.77 2019 aarch64 GNU/Linux，用的最新源码编译。

命令行运行： `http-proxy --config=/root/cfg/http-proxy.config -v --log-level=7`，然后用 Ctrl+C 结束，再次运行，一直提示：

```
init_listen() error: bind() error: 0.0.0.0:55555 errno=98, Address already in use
init_listens() error
```

需要几十秒或者 1分来钟才能再次运行。

**Comment by GangZhuo** [comment]
fixed
